"""add unique constraint for slug

Revision ID: 183e4f73c9fe
Revises: 292226fc1fbb
Create Date: 2024-06-11 10:43:00.809999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183e4f73c9fe'
down_revision = '292226fc1fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
